/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Auto-activate a new SW as soon as it's installed (don't wait for the user to
// tap "Update"). Combined with clientsClaim() + the registration's
// controllerchange→reload, this makes every deploy self-heal: a client stuck on
// a broken cached shell recovers on its next open instead of staying blank.
self.skipWaiting();
clientsClaim();

// Precache all static assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// SPA navigations: NETWORK-FIRST so a deploy is picked up immediately and a
// stale/evicted precache can never serve a shell that points at deleted JS
// chunks (which left a blank screen). Falls back to the precached index.html
// only when the network fails (offline).
const shellFallback = createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html');
const shellNetworkFirst = new NetworkFirst({ cacheName: 'app-shell', networkTimeoutSeconds: 4 });
const navigationHandler = async (params) => {
  try {
    const res = await shellNetworkFirst.handle(params);
    if (res) return res;
  } catch (e) {
    /* offline → fall through to the precached shell */
  }
  return shellFallback(params);
};
registerRoute(
  new NavigationRoute(navigationHandler, {
    denylist: [
      /\/manifest\.json$/,
      /\/service-worker\.js$/,
      /\/asset-manifest\.json$/,
      /\/favicon\.ico$/,
      /\/robots\.txt$/,
      /\/apple-touch-icon.*\.png$/,
    ],
  })
);

// API: Game data - NetworkFirst with short timeout
// Shows fresh data when online, falls back to cache when offline
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/getGames'),
  new NetworkFirst({
    cacheName: 'game-data',
    networkTimeoutSeconds: 5,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 5 * 60, // 5 min cache for offline fallback
      }),
    ],
  })
);

// API: Team list - StaleWhileRevalidate (data changes rarely, 1h backend cache)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/getTeams'),
  new StaleWhileRevalidate({
    cacheName: 'team-data',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 5,
        maxAgeSeconds: 60 * 60, // 1 hour
      }),
    ],
  })
);

// API: Schedule data - NetworkFirst
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/schedule'),
  new NetworkFirst({
    cacheName: 'schedule-data',
    networkTimeoutSeconds: 5,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 5,
        maxAgeSeconds: 60 * 60, // 1 hour
      }),
    ],
  })
);

// API: Image proxy - CacheFirst (team logos rarely change)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/getImage'),
  new CacheFirst({
    cacheName: 'team-logos',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 300, // league-wide distinct logos; deduped by image file
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  })
);

// External images (tulospalvelu logos in dev mode)
registerRoute(
  ({ url }) => url.hostname === 'tulospalvelu.leijonat.fi' && url.pathname.includes('/images/'),
  new CacheFirst({
    cacheName: 'external-logos',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60,
      }),
    ],
  })
);

// Jopox team photos (player/official rosters) - CacheFirst, big + long-lived
registerRoute(
  ({ url }) => url.hostname === 'static.jopox.fi',
  new CacheFirst({
    cacheName: 'jopox-images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 300, // a full roster has dozens of photos; several teams
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days (Jopox sends max-age=30d too)
      }),
    ],
  })
);

// Google Fonts / other CDN assets
registerRoute(
  ({ url }) => url.origin !== self.location.origin && !url.pathname.includes('/api/'),
  new StaleWhileRevalidate({
    cacheName: 'cdn-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Listen for skip waiting message from registration
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
