/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

clientsClaim();

// Precache all static assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// SPA: serve index.html for all navigation requests
const handler = createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html');
registerRoute(
  new NavigationRoute(handler, {
    denylist: [
      /\/manifest\.json$/,
      /\/service-worker\.js$/,
      /\/asset-manifest\.json$/,
      /\/favicon\.ico$/,
      /\/robots\.txt$/,
      /\/apple-touch-icon.*\.png$/,
    ],
  })
);

// API: Game data - NetworkFirst with short timeout
// Shows fresh data when online, falls back to cache when offline
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/getGames'),
  new NetworkFirst({
    cacheName: 'game-data',
    networkTimeoutSeconds: 5,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 5 * 60, // 5 min cache for offline fallback
      }),
    ],
  })
);

// API: Team list - StaleWhileRevalidate (data changes rarely, 1h backend cache)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/getTeams'),
  new StaleWhileRevalidate({
    cacheName: 'team-data',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 5,
        maxAgeSeconds: 60 * 60, // 1 hour
      }),
    ],
  })
);

// API: Schedule data - NetworkFirst
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/schedule'),
  new NetworkFirst({
    cacheName: 'schedule-data',
    networkTimeoutSeconds: 5,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 5,
        maxAgeSeconds: 60 * 60, // 1 hour
      }),
    ],
  })
);

// API: Image proxy - CacheFirst (team logos rarely change)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/getImage'),
  new CacheFirst({
    cacheName: 'team-logos',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  })
);

// External images (tulospalvelu logos in dev mode)
registerRoute(
  ({ url }) => url.hostname === 'tulospalvelu.leijonat.fi' && url.pathname.includes('/images/'),
  new CacheFirst({
    cacheName: 'external-logos',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60,
      }),
    ],
  })
);

// Google Fonts / other CDN assets
registerRoute(
  ({ url }) => url.origin !== self.location.origin && !url.pathname.includes('/api/'),
  new StaleWhileRevalidate({
    cacheName: 'cdn-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Listen for skip waiting message from registration
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
